### ISSUE TITLE
ISNETpro Traceback error

### ISSUE THREAD

**Issue by Tobe2d** [ClockZinc/sd-webui-IS-NET-pro#2]
When I try teststing ISNETpro I am getting this error:

```

 IS-NET_pro: start generating...
  0%|                                                                                                             | 0/150 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\extensions\sd-webui-IS-NET-pro\isnet_pro\Inference.py", line 132, in pic_generation
    IS_inference(img_mode,dataset_path,background_path,result_path,ui_set_aim_bacground_rgb,IS_recstrth)
  File "E:\stable-diffusion-webui\extensions\sd-webui-IS-NET-pro\isnet_pro\Inference.py", line 211, in IS_inference
    bc_path = bc_list[i]
IndexError: list index out of range
```

Screen shot of the tab:
![image](https://user-images.githubusercontent.com/4099839/230741725-7574b4e2-b568-4308-927f-9a1fe7efaffa.png)

**Comment by ClockZinc** [comment]
OK, I will fix it soon

**Comment by ClockZinc** [comment]
Background input dir should not be "folder\\image.png", it should be a "input\\folder"

**Comment by Tobe2d** [comment]
where the input folder should be located? 
as I try and it did not work ;-(

should it be in stable-diffusion-webui/input 
or
stable-diffusion-webui\extensions\sd-webui-IS-NET-pro/input 

I cant get it to work

If you can provide more information it will be really helpful 🙏

**Comment by ClockZinc** [comment]
input folder can be anywhere in you device. It should be like D:\path\to\folder .
![image](https://user-images.githubusercontent.com/118424801/230843907-9432dc93-ac32-4846-bc85-4a80014bfe99.png)
By the way, does it download any pth?
as shown in follows, the folder has a iamge(can be more), I fill in the path of it
![image](https://user-images.githubusercontent.com/118424801/230844923-2343a923-b9cf-43c2-8aa2-904faf70a60e.png)
The output folder, has nothing in it(it could have some)
![image](https://user-images.githubusercontent.com/118424801/230844367-80d4bc33-62d5-4085-a4eb-02ab9d390e23.png)
Then click the gene_frame button
![image](https://user-images.githubusercontent.com/118424801/230844690-f517e2d5-0ff1-4c09-8e05-fe28d61ad026.png)
Then it generates a image with white background
![image](https://user-images.githubusercontent.com/118424801/230845020-522d7d80-af1f-4677-9d30-3eace505d390.png)

**Comment by Tobe2d** [comment]
@ClockZinc it is working now ;-)

Thank you so much!

Another small bug i think, Regarding frame output mode, I cant select anything otherthan white background, I was trying to select Alpha channel and it keep the white background.


![image](https://user-images.githubusercontent.com/4099839/230967154-5d5a72a9-09f5-4270-89be-e3f855d8fc14.png)

**Comment by ClockZinc** [comment]
Maybe it is because you uses the auto-translation mode, you can try to select the alpha_channel mode and check whether the background become tansparent

**Comment by Tobe2d** [comment]
Yes you are right. when I select it, the menue does not change  but it work nicely with alpha.
